// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bio: dynamic(() => import("./Bio")),
  contact_index: dynamic(() => import("./ContactIndex")),
  hero: dynamic(() => import("./Hero")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
};
